language: python
python:
  - "3.6"
  - "3.7"
install:
- pip install --upgrade -r requirements.txt
- pip install python-coveralls coverage pytest-sugar
- py.test --version
- python setup.py develop
script:
- py.test -v --cov=linlearn
after_success: coveralls
cache:
  directories:
    - $HOME/linlearn
